name = "master-router"
main = "src/index.js"
compatibility_date = "2024-11-18"

# Masukkan semua domain kamu di sini (Wildcard)
# Ini menggantikan setting manual di Dashboard Triggers
routes = [
		
		{ pattern = "*.smilespirit.uk/*", zone_name = "smilespirit.uk" },
		{ pattern = "*.cenulmania.my.id/*", zone_name = "cenulmania.my.id" }
]














